# -*- coding: utf-8 -*-
"""OSS_과제_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBxBV02S0xQO2oabhDB2FqA2Tz6-r4gY
"""

#데이터 셋 다운로드
from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler #스케일러 추가

wine = datasets.load_wine()
print(wine)
print(wine.target_names)

#훈련 데이터 및 테스트 데이터 분리
X = wine.data
y = wine.target

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, random_state=109)
scaler = StandardScaler()                         #데이터 스케일링
X_train_scaled = scaler.fit_transform(X_train)    #훈련 데이터로 스케일링 기준 학습 및 변환
X_test_scaled = scaler.transform(X_test)

print(X_train.shape)
print(X_test.shape)

#학습
knn = KNeighborsClassifier(n_neighbors=5) #6에서 5으로 변경
knn.fit(X_train_scaled, y_train) #X_train -> X_train_scaled 변경

#정확도
y_pred = knn.predict(X_test_scaled)

score = metrics.accuracy_score(y_test, y_pred)
print(f"{score: .4f}")

#예측
classes = wine.target_names

x_new = [[5, 2, 3, 5, 1, 0.6, 23, 54, 22, 14, 7, 2, 500],
         [13, 0.2, 1, 9.5, 4, 26, 18, 4.5, 22, 6.3, 4, 16, 2.3]]

x_new_scaled = scaler.transform(x_new)
y_predict = knn.predict(x_new)

print(classes[y_predict[0]])
print(classes[y_predict[1]])



"""----------------------------------------------"""