# -*- coding: utf-8 -*-
"""OSS_과제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ji3yej56lGhHwExwJPaxma9WtbAV7wEh
"""

#데이터 셋 다운로드
from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

wine = datasets.load_wine()
print(wine)
print(wine.target_names)

#훈련 데이터 및 테스트 데이터 분리
X = wine.data
y = wine.target

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, random_state=109)

print(X_train.shape)
print(X_test.shape)

#학습
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)

#정확도
y_pred = knn.predict(X_test)

score = metrics.accuracy_score(y_test, y_pred)
print(score)

#예측
classes = wine.target_names

x_new = [[5, 2, 3, 5, 1, 0.6, 23, 54, 22, 14, 7, 2, 500],
 [13, 0.2, 1, 9.5, 4, 26, 18, 4.5, 22, 6.3, 4, 16, 2.3]]

y_predict = knn.predict(x_new)

print(classes[y_predict[0]])
print(classes[y_predict[1]])



"""----------------------------------------------"""